export type Locale = 'en' | 'fa';

const en = {
  meta: { title: 'Babalridha Academic & Spiritual Institute', description: 'A holistic institute for scholarship, spiritual growth, practical skills, and family flourishing.' },
  nav: { about: 'About', curriculum: 'Curriculum', family: 'Family', outcomes: 'Outcomes', departments: 'Departments', faculty: 'Faculty', portal: 'Portal Login', apply: 'Apply for Admission', language: 'فارسی' },
  hero: { eyebrow: 'Academic & Spiritual Institute', title: 'Cultivating the Integrated Human at the Horizon of', highlight: 'Modern Islamic Civilization', desc: 'A vibrant environment for academic excellence, practical skills, moral refinement, and family empowerment under exemplary mentorship.', video: 'Watch Documentary', imageTag: 'From Learning to Community Impact', imageTitle: 'Deep Scholarship, Spiritual Elevation & Readiness' },
  about: { title: 'The Urgent Need and Guiding Philosophy', subtitle: 'A unified pathway under continuous scholarly oversight, refined over 15 years.', cards: [['Need for an Integrated System','A synergistic model uniting scholarly depth, spiritual discipline, and practical capabilities.','compass'],['Guided by Exemplary Mentorship','Senior scholarly masters provide dependable, personal guidance throughout the journey.','shield-check'],['Continuous 15-Year Growth','From a dedicated study group to a growing network of graduates and global outreach.','trending-up']], bannerTitle: '15 Years of Evolution', bannerDesc: 'Dozens of specialized curricula, rigorous benchmarks, and training workshops shaped by the needs of contemporary seekers.' },
  curriculum: { title: 'The Four Pillars of the Institute', subtitle: 'A balanced architecture for a complete life', tabs: [['Academic & Scholarly','Structured Curriculum and Rigorous Scholarship','Research-oriented inquiry, dialectic debate, regular assessment, and close faculty mentorship.',['Rational sciences, jurisprudence, theology, and philosophy','Cohort discussion and weekly assessment','Personalized academic advising'],'graduation-cap'],['Spiritual & Moral','Spiritual Elevation & Moral Refinement','Knowledge is joined to spiritual purification through devotion, retreats, and guided self-accounting.',['Contemplative retreats and morning invocations','Individual spiritual counseling','Guided pilgrimage and sacred traditions'],'heart-handshake'],['Recreation & Athletics','Vitality, Fitness & Brotherhood','Nature expeditions, sports, and joyful gatherings are integral to the annual calendar.',['Mountaineering and wilderness camps','Swimming, futsal, archery, and martial arts','Family festivals and seasonal excursions'],'mountain'],['Applied Skills & Media','Contemporary Tools for Service','Graduates learn to communicate truth through modern media, languages, and organization.',['Public speaking and rhetoric','Digital content and creative writing','English and Arabic for global discourse'],'laptop']] },
  family: { title: 'The Babalridha Family', subtitle: 'Individual excellence flourishes when the whole family grows together.', cards: [['Women’s Scholarly Needs','Structured theological learning and contemporary forums.','book-open'],['Women’s Seminary Division','An independent path for higher Islamic studies.','landmark'],['Family Joy & Spirituality','Pilgrimages, celebrations, and shared spiritual circles.','heart'],['Holistic Life Support','Counseling, parenting support, and mutual welfare.','users']] },
  outcomes: { title: 'Strategic Achievements & Institutional Outcomes', subtitle: 'Scholarly, ethical, and practical dedication translated into public good.', items: [['Educational Leaders','Training pioneering directors, mentors, and counselors.'],['Research & Translation','Publishing research and translating core Islamic works.'],['Specialized Courses','Intensive modules and teacher-training programs.'],['Community Service','Sustained humanitarian work in underserved regions.'],['Youth Literature & Art','Value-driven fiction, podcasts, and animation.'],['Organizational Synergy','Practical teamwork, discipline, and project leadership.']] },
  departments: { title: 'Departments', subtitle: 'Specialized divisions for education, research, content, and youth development', items: [['BRISC','Intensive Short Course','A three-week immersive summer program.'],['OLP','Online Learning Platform','Self-paced, standardized Islamic learning.'],['RP','Research & Publication','Classical and analytical works for contemporary minds.'],['Ahsan','Gap Year Program','Eight months of study, discipline, and leadership.'],['Arbaeen Backpackers','Pilgrimage','A mentored walking caravan to Karbala.'],['Lectures','Recorded Sessions','An archive of talks by distinguished faculty.'],['Raising Them Ready','Parents','Tools for raising resilient and faithful children.'],['BRi Kids!','Children & Teens','Stories and activities that reinforce faith.']] },
  video: { title: 'Discover Babalridha Institute', desc: 'A glimpse into academic life, brotherhood, service, and our supportive family atmosphere.' },
  faculty: { title: 'Leadership & Faculty', subtitle: 'Guidance by distinguished seminary and university scholars.', members: [['Hujjatul Islam Amini','Head of Institute','agha-amini.jpg'],['Shaykh Miqdad Rajabali','Assistant Head','MR.jpg'],['Shaykh Muhammad Baqir Sadiq','Hawzah Management','MBS.jpg'],['Syed Ruhullah Mosawi','Hawzah Management','SRM.jpg']] },
  cta: { title: 'Ready to Join the Babalridha Family?', desc: 'Begin a transformative journey of scholarship, refinement, and practical mastery.', button: 'Complete Online Application' },
  footer: { name: 'Babalridha Academic & Spiritual Institute', desc: 'Nurturing comprehensive leaders through education, self-refinement, and family empowerment.', rights: 'All rights reserved.' },
  apply: { title: 'New Academic Year Admission Application', intro: 'Please complete every section carefully. Your application will be reviewed by the admissions board.', formTitle: 'Student Application Form', submit: 'Submit Application', submitting: 'Submitting…', error: 'We could not submit your application. Please check the form and try again.', success: 'Thank you. Your application has been prepared for submission.', sections: ['Personal Information','Education Information','Religious Education','Interests & Activities','Skills','Family Information','Personality Questions','Administrative & Welfare'], fields: { first_name:'First Name',last_name:'Last Name',phone:'Mobile Number',email:'Email',birth_date:'Date of Birth',birth_place:'Place of Birth',photo:'Applicant Photo',last_degree:'Last Education Degree',field_of_study:'Field of Study',education_city:'City of Study',average_grade:'Average Grade',quran_memorization:'Quran Memorization',religious_studies:'Religious Sciences Education',hawza_entry_year:'Year of Entry to Hawza',hawza_education:'Hawza Education',favorite_hawza_lessons:'Favorite Hawza Lessons',intended_stay_duration:'Intended Duration of Stay in Iran',parents_satisfaction:'Parents’ Satisfaction',intended_specialization:'Intended Hawza Specialization',current_occupation:'Current Occupation or Education',books_read:'Books You Have Read',favorite_scholars:'Scholars and Speakers You Follow',followed_online_sources:'Websites and Channels You Follow',favorite_movies:'Movies and Series You Like',role_models:'Your Role Models',interests:'Your Interests',cultural_activities:'Cultural or Community Activities',skills_list:'Skills',skills_experience:'Experience with These Skills',father_name:'Father’s Name',father_birth_year:'Father’s Birth Year',father_job:'Father’s Job',mother_name:'Mother’s Name',mother_birth_year:'Mother’s Birth Year',mother_job:'Mother’s Job',siblings_count:'Number of Siblings',marital_status:'Marital Status',social_behavior:'How do you describe your social behavior?',info_outlook:'How do you approach new information?',decision_making:'How do you make decisions?',planning_style:'How do you plan?',nationality:'Nationality',passport_number:'Passport Number',student_code:'Student Code (Talabegi)',eitaa_number:'Eitaa Number',address:'Home or Dormitory Address'} }
};

const fa: typeof en = {
  ...en,
  meta: { title: 'مؤسسه علمی و تربیتی باب‌الرضا', description: 'مؤسسه‌ای جامع برای رشد علمی، معنوی، مهارتی و خانوادگی.' },
  nav: { about:'درباره ما',curriculum:'برنامه تربیتی',family:'خانواده',outcomes:'دستاوردها',departments:'مجموعه‌ها',faculty:'اساتید',portal:'ورود به سامانه',apply:'ثبت‌نام پذیرش',language:'English' },
  hero: { eyebrow:'مؤسسه علمی و تربیتی',title:'پرورش انسان جامع در افق',highlight:'تمدن نوین اسلامی',desc:'محیطی پویا برای تعالی علمی، مهارت‌های کاربردی، تهذیب اخلاقی و توانمندسازی خانواده، زیر نظر اساتید الگو.',video:'مشاهده مستند',imageTag:'از آموزش تا اثرگذاری اجتماعی',imageTitle:'دانش عمیق، رشد معنوی و آمادگی برای خدمت' },
  about: { title:'ضرورت و فلسفه راهنما',subtitle:'مسیر یکپارچه‌ای که طی پانزده سال زیر نظر مستمر اساتید فرهیخته تکامل یافته است.',cards:[['نیاز به نظام جامع','الگویی هم‌افزا که عمق علمی، انضباط معنوی و توانایی‌های عملی را پیوند می‌دهد.','compass'],['هدایت استادان الگو','اساتید برجسته در تمام مسیر، راهنمایی شخصی و قابل اعتماد ارائه می‌کنند.','shield-check'],['پانزده سال رشد پیوسته','از یک حلقه علمی تا شبکه‌ای رو به رشد از دانش‌آموختگان و فعالیت‌های بین‌المللی.','trending-up']],bannerTitle:'پانزده سال تحول و بالندگی',bannerDesc:'ده‌ها برنامه تخصصی، معیارهای دقیق و کارگاه‌های آموزشی متناسب با نیازهای امروز.' },
  curriculum: { title:'چهار رکن مؤسسه',subtitle:'معماری متعادل برای ساختن یک زندگی جامع',tabs:[['علمی و آموزشی','برنامه منظم و پژوهش عمیق','پژوهش مسئله‌محور، مباحثه، ارزیابی منظم و همراهی نزدیک استادان.',['علوم عقلی، فقه، کلام و فلسفه','مباحثه گروهی و ارزیابی هفتگی','مشاوره علمی شخصی'],'graduation-cap'],['معنوی و اخلاقی','تعالی معنوی و تهذیب اخلاق','دانش با خودسازی، عبادت، خلوت‌های معنوی و محاسبه نفس همراه می‌شود.',['اعتکاف و مناجات سحرگاهی','مشاوره معنوی فردی','زیارت و انس با سنت‌های دینی'],'heart-handshake'],['تفریحی و ورزشی','نشاط، آمادگی و برادری','طبیعت‌گردی، ورزش و برنامه‌های شاد بخش جدایی‌ناپذیر تقویم سالانه‌اند.',['کوهنوردی و اردوهای طبیعت','شنا، فوتسال، تیراندازی و رزمی','جشنواره‌های خانوادگی'],'mountain'],['مهارت و رسانه','ابزارهای امروز برای خدمت','طلاب شیوه انتقال حقیقت با رسانه، زبان و مدیریت نوین را می‌آموزند.',['سخنرانی و فن بیان','تولید محتوای دیجیتال','زبان انگلیسی و عربی'],'laptop']] },
  family:{title:'خانواده باب‌الرضا',subtitle:'رشد فردی وقتی شکوفا می‌شود که تمام خانواده هم‌زمان تعالی یابد.',cards:[['نیازهای علمی بانوان','آموزش‌های منظم دینی و نشست‌های روزآمد.','book-open'],['حوزه علمیه خواهران','مسیر مستقل تحصیلات عالی اسلامی.','landmark'],['نشاط و معنویت خانواده','زیارت، جشن و حلقه‌های معنوی مشترک.','heart'],['پشتیبانی جامع زندگی','مشاوره، فرزندپروری و حمایت متقابل.','users']]},
  outcomes:{title:'دستاوردها و نتایج راهبردی',subtitle:'تبدیل تلاش علمی، اخلاقی و عملی به خیر عمومی.',items:[['مدیران آموزشی','پرورش مدیران، مربیان و مشاوران پیشرو.'],['پژوهش و ترجمه','انتشار پژوهش و ترجمه آثار اصلی اسلامی.'],['دوره‌های تخصصی','دوره‌های فشرده و تربیت مدرس.'],['خدمت اجتماعی','فعالیت مستمر جهادی در مناطق محروم.'],['ادبیات و هنر کودک','داستان، پادکست و پویانمایی ارزش‌محور.'],['هم‌افزایی سازمانی','کار گروهی، انضباط و رهبری پروژه.']]},
  departments:{title:'مجموعه‌ها',subtitle:'بخش‌های تخصصی آموزش، پژوهش، محتوا و تربیت نسل جوان',items:[['BRISC','دوره فشرده کوتاه‌مدت','برنامه تابستانی سه‌هفته‌ای و عمیق.'],['OLP','آموزش آنلاین','یادگیری استاندارد و خودگام اسلامی.'],['RP','پژوهش و نشر','آثار اسلامی برای ذهن معاصر.'],['Ahsan','دوره یک‌ساله','هشت ماه آموزش، خودسازی و رهبری.'],['Arbaeen Backpackers','زیارت','کاروان پیاده اربعین همراه مربیان.'],['سخنرانی‌ها','جلسات ضبط‌شده','آرشیو سخنرانی استادان برجسته.'],['آماده‌شان کنیم','والدین','ابزار تربیت نسلی مقاوم و مؤمن.'],['BRi Kids!','کودک و نوجوان','داستان‌ها و فعالیت‌های جذاب ایمانی.']]},
  video:{title:'با مؤسسه باب‌الرضا آشنا شوید',desc:'نمایی از زندگی علمی، برادری، خدمت اجتماعی و فضای صمیمی خانواده ما.'},
  faculty:{title:'مدیریت و اساتید',subtitle:'هدایت علمی توسط استادان برجسته حوزه و دانشگاه.',members:[['حجت‌الاسلام امینی','مدیر مؤسسه','agha-amini.jpg'],['شیخ مقداد رجبعلی','معاون مؤسسه','MR.jpg'],['شیخ محمدباقر صادق','مدیریت حوزه','MBS.jpg'],['سید روح‌الله موسوی','مدیریت حوزه','SRM.jpg']]},
  cta:{title:'آماده‌اید به خانواده باب‌الرضا بپیوندید؟',desc:'سفر تحول‌آفرین دانش، خودسازی و مهارت عملی را آغاز کنید.',button:'تکمیل فرم پذیرش'},
  footer:{name:'مؤسسه علمی و تربیتی باب‌الرضا',desc:'پرورش مدیران جامع از مسیر آموزش، خودسازی و توانمندسازی خانواده.',rights:'تمامی حقوق محفوظ است.'},
  apply:{...en.apply,title:'فرم درخواست پذیرش سال تحصیلی جدید',intro:'لطفاً همه بخش‌ها را با دقت تکمیل کنید. درخواست شما توسط هیئت پذیرش بررسی خواهد شد.',formTitle:'فرم پذیرش طلبه',submit:'ثبت درخواست',submitting:'در حال ارسال…',error:'ارسال درخواست انجام نشد. لطفاً اطلاعات فرم را بررسی کرده و دوباره تلاش کنید.',success:'سپاسگزاریم. اطلاعات شما برای ارسال آماده شد.',sections:['مشخصات فردی','اطلاعات تحصیلی','تحصیلات دینی','علایق و فعالیت‌ها','مهارت‌ها','اطلاعات خانواده','پرسش‌های شخصیتی','اطلاعات اداری و رفاهی'],fields:{first_name:'نام',last_name:'نام خانوادگی',phone:'شماره همراه',email:'ایمیل',birth_date:'تاریخ تولد',birth_place:'محل تولد',photo:'عکس متقاضی',last_degree:'آخرین مدرک تحصیلی',field_of_study:'رشته تحصیلی',education_city:'شهر محل تحصیل',average_grade:'معدل آخرین مقطع',quran_memorization:'میزان حفظ قرآن',religious_studies:'تحصیلات علوم دینی',hawza_entry_year:'سال ورود به حوزه',hawza_education:'تحصیلات حوزوی',favorite_hawza_lessons:'دروس حوزوی مورد علاقه',intended_stay_duration:'مدت اقامت مورد نظر در ایران',parents_satisfaction:'میزان رضایت والدین',intended_specialization:'گرایش تخصصی مورد نظر در حوزه',current_occupation:'شغل یا تحصیل فعلی',books_read:'کتاب‌های مطالعه‌شده',favorite_scholars:'استادان و سخنرانان مورد علاقه',followed_online_sources:'سایت‌ها و کانال‌های مورد پیگیری',favorite_movies:'فیلم‌ها و سریال‌های مورد علاقه',role_models:'الگوهای شما',interests:'علایق شما',cultural_activities:'فعالیت‌های فرهنگی یا اجتماعی',skills_list:'مهارت‌ها',skills_experience:'تجربه شما در این مهارت‌ها',father_name:'نام پدر',father_birth_year:'سال تولد پدر',father_job:'شغل پدر',mother_name:'نام مادر',mother_birth_year:'سال تولد مادر',mother_job:'شغل مادر',siblings_count:'تعداد خواهر و برادر',marital_status:'وضعیت تأهل',social_behavior:'رفتار اجتماعی خود را چگونه توصیف می‌کنید؟',info_outlook:'با اطلاعات جدید چگونه مواجه می‌شوید؟',decision_making:'چگونه تصمیم می‌گیرید؟',planning_style:'چگونه برنامه‌ریزی می‌کنید؟',nationality:'ملیت',passport_number:'شماره گذرنامه',student_code:'کد طلبگی',eitaa_number:'شماره ایتا',address:'نشانی منزل یا خوابگاه'}}
};

export const translations = { en, fa };
export const getTranslation = (locale: Locale) => translations[locale];
